### ISSUE TITLE
How to change the font type of editor when editing.

### ISSUE THREAD

**Issue by tensor2077** [Natchamon/MyBackpack#1]
![image](https://user-images.githubusercontent.com/38134733/81702450-e15d8400-949d-11ea-9d14-c54c1acc4969.png)

The font type of the editor is different from the font of the editor you are editing. Is there a way to make them consistent?
Thanks.

**Comment by Natchamon** [comment]
![image](https://user-images.githubusercontent.com/65183911/81735658-92284b00-94bf-11ea-877e-919b1e5243b9.png)
Add this line with your preferred font.

**Comment by Natchamon** [comment]
![Add this line](https://user-images.githubusercontent.com/65183911/81735856-e4696c00-94bf-11ea-8929-9d36787c678d.png)
Add this line with your preferred font family. in the /*Selection Style*/ section

**Comment by tensor2077** [comment]
Thanks. @Natchamon 
It works.
